image: python:3.10

stages:
  - build
  - deploy

variables:
  APP_DIR: "/build"

cache:
  paths:
    - venv/

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip

build_app:
  stage: build
  script:
    - pip install -r requirements.txt
    - echo "✅ Build successful — Dependencies installed."
    - mkdir -p $APP_DIR
    - cp -r . $APP_DIR
  artifacts:
    paths:
      - $APP_DIR
    expire_in: 1 hour
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

deploy_app:
  stage: deploy
  dependencies:
    - build_app
  script:
    - cd $APP_DIR
    - source venv/bin/activate
    - python app.py
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
