[build]
command = "pip install -r requirements.txt"
base = "/"
publish = "/"

[build.environment]
PYTHONPATH = "."

# Exclude the model file from the build
[[redirects]]
  from = "/models/*"
  to = "/404.html"
  status = 404
